### ISSUE TITLE
文本不换行/换行/超出自动省略号

### ISSUE THREAD

**Issue by langnang** [langnang/list-of-knowledge-and-skills#2]
## 强制不换行
```css
div{
   white-space:nowrap;
}
```
## 强制英文单词换行
```css
div{
   word-break:break-all;
}
```
## 自动换行
```css
div{
   word-wrap:break-word;
   word-break:normal;
}
```

## 单行文本不换行多余文本显示省略号
```css
div{
   width:200px;
   white-space:nowrap;
   overflow:hidden;
   text-overflow:ellipsis;
}
```
## 多行文本超出隐藏多余文本显示省略号
```css
div{
   display:-webkit-box;
   overflow:hidden;
   text-overflow:ellipsis;
   -webkit-line-clamp:3;
   -webkit-box-orient:vertical;
}
```

## table表格中单元格单行文本不换行
```css
table{
   table-layout:fixed;
}
table tr td{
   width:60%;
   white-space:nowrap;
   overflow:hidden;
   text-overflow:ellipsis;
}
```
