### ISSUE TITLE
CSS之盒子水平垂直居中

### ISSUE THREAD

**Issue by langnang** [langnang/list-of-knowledge-and-skills#4]
```html
<div id="box">
    <div id="box1">

    </div>
</div>
```
## 宽度和高度已知的
```css
#box{
    width: 400px;
    height: 200px;
    position: relative;
    background: red;
}
#box1{
    width: 200px;
    height: 100px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: -100px;
    margin-top: -50px;
    background: green;
}
```
## 宽度和高度未知
```css
#box{
    width: 800px;
    height: 400px;
    position: relative;
    background: red;
}
#box1{
    width: 100px;
    height: 50px;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
    background: green;
}
```
## flex 布局
```css
#box{
    width: 400px;
    height: 200px;
    background: #f99;
    display: flex;
    justify-content: center;//实现水平居中
    align-items: center;//实现垂直居中
}
#box1{
    width: 200px;
    height: 100px;
    background: green;
}
```
## 平移 定位+transform
```css
#box{
    width: 400px;
    height: 200px;
    background: red;
    position: relative;
}
#box1{
    width: 200px;
    height: 100px;
    background: #9ff;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```
## table-cell 布局
```css
#box{
    display: table-cell;
    vertical-align: middle
}
#box1{
    margin: 0 auto;
}
```
